.page{--navy:#0b1f3a;--navy2:#12345b;--orange:#f58220;--ink:#142033;--muted:#64748b;--line:#dbe4ee;background:#fff;color:var(--ink)}
.container{width:min(1180px,calc(100% - 40px));margin:0 auto}
.hero{position:relative;overflow:hidden;background:linear-gradient(112deg,#081a31 0%,#12345b 72%,#174771 100%);color:#fff;padding:54px 0 60px}
.hero:after{content:"";position:absolute;right:-180px;top:-220px;width:620px;height:620px;border:1px solid rgba(255,255,255,.12);border-radius:50%;box-shadow:0 0 0 80px rgba(255,255,255,.025),0 0 0 160px rgba(255,255,255,.02)}
.heroInner{position:relative;z-index:1;display:grid;grid-template-columns:minmax(0,1.35fr) minmax(300px,.65fr);align-items:center;gap:44px}
.heroCopy{min-width:0}
.eyebrow{margin:0 0 14px;color:#ffad68;font-weight:800;letter-spacing:.08em;text-transform:uppercase;font-size:13px}
.hero h1{max-width:850px;margin:0;font-size:clamp(36px,4.4vw,60px);line-height:1.04;letter-spacing:-.035em;color:#fff}
.lead{max-width:850px;margin:22px 0 0;color:rgba(255,255,255,.84);font-size:clamp(18px,2vw,23px);line-height:1.5}
.benefits{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px 24px;max-width:870px;margin:27px 0 0;padding:0;list-style:none}
.benefits li{position:relative;padding-left:25px;color:#fff;font-size:16px}.benefits li:before{content:"✓";position:absolute;left:0;color:#ff9a45;font-weight:900}
.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:31px}
.primary,.secondary{appearance:none;border-radius:12px;min-height:52px;padding:13px 22px;border:1px solid transparent;font:inherit;font-weight:800;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;text-decoration:none;transition:transform .18s ease,box-shadow .18s ease,background .18s ease}
.primary{background:var(--orange);color:#fff;box-shadow:0 12px 30px rgba(245,130,32,.25)}.primary:hover{transform:translateY(-2px);background:#ff8d2c}.secondary{background:#fff;color:var(--navy);border-color:#fff}.secondary:hover{transform:translateY(-2px);box-shadow:0 12px 30px rgba(0,0,0,.18)}
.micro{margin:15px 0 0;color:rgba(255,255,255,.62);font-size:13px}
.heroVisual{position:relative;margin:0;overflow:hidden;border-radius:22px;border:1px solid rgba(255,255,255,.16);background:#0d2948;box-shadow:0 30px 70px rgba(0,0,0,.28)}
.heroVisual img{display:block;width:100%;height:460px;object-fit:cover;object-position:center}
.heroVisual figcaption{position:absolute;left:14px;right:14px;bottom:14px;padding:12px 14px;border:1px solid rgba(255,255,255,.16);border-radius:12px;background:rgba(7,23,42,.82);backdrop-filter:blur(8px);color:#fff;font-size:13px;font-weight:750;line-height:1.35}
.section{padding:76px 0}.soft{background:#f5f8fb}.dark{background:var(--navy);color:#fff}
.sectionHead{max-width:790px;margin-bottom:34px}.sectionHead p{margin:10px 0 0;color:var(--muted);font-size:18px;line-height:1.55}.dark .sectionHead p{color:rgba(255,255,255,.7)}
.section h2{margin:0;color:var(--navy);font-size:clamp(29px,3.5vw,44px);line-height:1.12;letter-spacing:-.025em}.dark h2{color:#fff}
.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{position:relative;overflow:hidden;min-height:300px;padding:28px;border:1px solid var(--line);border-radius:20px;background:#fff;box-shadow:0 16px 48px rgba(19,43,72,.07)}
.cardNo{display:flex;width:42px;height:42px;align-items:center;justify-content:center;border-radius:12px;background:#eef4fa;color:var(--orange);font-weight:900}.card h3{margin:54px 0 12px;color:var(--navy);font-size:24px;line-height:1.2}.card p{margin:0;color:var(--muted);line-height:1.55}.card:after{content:"";position:absolute;right:-42px;top:-42px;width:140px;height:140px;border-radius:50%;background:linear-gradient(145deg,rgba(245,130,32,.14),rgba(18,52,91,.03))}
.roomGrid,.valueGrid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px}.pill{min-height:126px;border-radius:16px;padding:20px;background:#fff;border:1px solid var(--line);font-weight:750;line-height:1.35;display:flex;flex-direction:column;justify-content:space-between}.pill span{color:var(--orange);font-size:13px}.valueGrid .pill{background:#102c4d;border-color:rgba(255,255,255,.1);color:#fff}.valueGrid .pill span{color:#ff9c4b}
.steps{display:grid;grid-template-columns:repeat(5,1fr);gap:0;counter-reset:step}.step{position:relative;padding:0 24px 0 0;counter-increment:step}.step:before{content:counter(step);display:flex;width:42px;height:42px;align-items:center;justify-content:center;border-radius:50%;background:var(--orange);color:#fff;font-weight:900;margin-bottom:18px}.step:not(:last-child):after{content:"";position:absolute;left:52px;right:12px;top:20px;height:2px;background:#d7e1ec}.step h3{margin:0;color:var(--navy);font-size:18px;line-height:1.35}
.cta{padding:48px 0;background:linear-gradient(112deg,#f58220,#e96608);color:#fff}.ctaInner{display:flex;align-items:center;justify-content:space-between;gap:28px}.cta h2{color:#fff;max-width:720px}.cta p{margin:10px 0 0;color:rgba(255,255,255,.84)}.cta .secondary{flex:0 0 auto}
.articleLink{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:28px;border:1px solid var(--line);border-radius:18px;background:#fff;text-decoration:none;color:var(--navy);transition:border-color .18s ease,transform .18s ease}.articleLink:hover{border-color:var(--orange);transform:translateY(-2px)}.articleLink strong{font-size:21px}.articleLink span{color:var(--orange);font-size:28px}
.modalBackdrop{position:fixed;inset:0;z-index:1000;background:rgba(5,17,31,.72);padding:22px;display:grid;place-items:center;overflow-y:auto}
.modal{position:relative;width:min(620px,100%);max-height:calc(100vh - 44px);overflow-y:auto;border-radius:22px;background:#fff;padding:30px;box-shadow:0 28px 90px rgba(0,0,0,.35)}
.close{position:absolute;right:16px;top:14px;width:40px;height:40px;border:0;border-radius:50%;background:#eef3f8;color:var(--navy);font-size:25px;cursor:pointer}.modal h2{padding-right:42px;margin:0;color:var(--navy);font-size:30px}.modalLead{color:var(--muted);line-height:1.5;margin:10px 0 22px}
.form{display:grid;gap:15px}.field{display:grid;gap:7px}.field label{font-weight:750;font-size:14px}.field input,.field textarea{width:100%;box-sizing:border-box;border:1px solid #cbd7e4;border-radius:11px;background:#fff;padding:13px 14px;font:inherit;color:var(--ink);outline:none}.field input:focus,.field textarea:focus{border-color:var(--orange);box-shadow:0 0 0 3px rgba(245,130,32,.12)}.field textarea{resize:vertical;min-height:98px}.fileHelp{font-size:12px;color:var(--muted)}
.consent{display:flex;align-items:flex-start;gap:9px;color:var(--muted);font-size:13px;line-height:1.4}.consent input{margin-top:3px}.consent a{color:var(--navy)}.status{margin:0;font-weight:700}.success{color:#15803d}.error{color:#b91c1c}
.fileName{font-size:13px;font-weight:750;color:var(--navy);overflow-wrap:anywhere}
.hiddenField{position:absolute!important;width:1px!important;height:1px!important;padding:0!important;margin:-1px!important;overflow:hidden!important;clip:rect(0,0,0,0)!important;white-space:nowrap!important;border:0!important}
.primary:focus-visible,.secondary:focus-visible,.close:focus-visible,.mobileBar button:focus-visible,.articleLink:focus-visible,.field input:focus-visible,.field textarea:focus-visible,.consent a:focus-visible{outline:3px solid #ffd0a8;outline-offset:3px}
.mobileBar{display:none}
@media(max-width:1050px){.heroInner{grid-template-columns:1fr}.heroVisual{display:none}}
@media(max-width:900px){.cards{grid-template-columns:1fr}.card{min-height:230px}.card h3{margin-top:34px}.roomGrid,.valueGrid{grid-template-columns:repeat(2,1fr)}.steps{grid-template-columns:1fr;gap:20px}.step{padding-left:62px;min-height:46px}.step:before{position:absolute;left:0;top:0;margin:0}.step:not(:last-child):after{left:20px;right:auto;top:47px;width:2px;height:20px}.ctaInner{align-items:flex-start;flex-direction:column}}
@media(max-width:640px){.container{width:min(100% - 28px,1180px)}.page{padding-bottom:72px}.hero{padding:34px 0 46px}.hero h1{font-size:38px}.lead{font-size:17px}.benefits{grid-template-columns:1fr;gap:9px}.actions{display:grid}.primary,.secondary{width:100%;padding-inline:14px}.section{padding:54px 0}.roomGrid,.valueGrid{grid-template-columns:1fr 1fr}.pill{min-height:102px;padding:16px;font-size:14px}.cta{padding:38px 0}.articleLink{align-items:flex-start}.articleLink strong{font-size:18px}.modalBackdrop{padding:10px}.modal{padding:24px 18px;border-radius:18px}.modal h2{font-size:25px}.mobileBar{position:fixed;z-index:900;left:0;right:0;bottom:0;display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:9px 10px calc(9px + env(safe-area-inset-bottom));background:rgba(8,26,49,.96);box-shadow:0 -8px 28px rgba(0,0,0,.2)}.mobileBar button{border:0;border-radius:9px;padding:11px 8px;font:inherit;font-size:12px;font-weight:800;line-height:1.2}.mobileBar button:first-child{background:var(--orange);color:#fff}.mobileBar button:last-child{background:#fff;color:var(--navy)}}
@media(max-width:390px){.hero h1{font-size:34px}.roomGrid,.valueGrid{grid-template-columns:1fr}.mobileBar button{font-size:11px}}
@media(prefers-reduced-motion:reduce){.primary,.secondary,.articleLink{transition:none}.primary:hover,.secondary:hover,.articleLink:hover{transform:none}}
